on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - uses: actions/checkout@v4
        with:
          repository: modelcontextprotocol/typescript-sdk
          ssh-key: ${{ secrets.TYPESCRIPT_SDK_KEY }}
          path: packages/@modelcontextprotocol/sdk

      - run: npm ci
        working-directory: packages/@modelcontextprotocol/sdk

      - run: npm pack
        working-directory: packages/@modelcontextprotocol/sdk

      - run: npm install --save packages/@modelcontextprotocol/sdk/modelcontextprotocol-sdk-*.tgz
      - run: npm ci
      - run: npm run build
